# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50)),
                ('category_date', models.DateTimeField(verbose_name=b'date category added')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=50)),
                ('photo_description', models.CharField(max_length=500)),
                ('photo_date', models.DateTimeField(verbose_name=b'date photo added')),
                ('category', models.ManyToManyField(to='photosite.Category')),
            ],
        ),
    ]
