# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_full',
            field=models.ImageField(default='', upload_to=b'full'),
            preserve_default=False,
        ),
    ]
