# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosite', '0003_auto_20160309_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name=b'Date category added'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_date',
            field=models.DateTimeField(help_text=b'When was the photo taken?', verbose_name=b'Date'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_full',
            field=models.ImageField(help_text=b'The full size image.', upload_to=b'full', verbose_name=b'Photo'),
        ),
    ]
